homepage:
    pattern:  /
    defaults: { _controller: SOTBCoreBundle:Default:index }

# ACCOUNT
members:
    pattern:  /member
    defaults: { _controller: SOTBCoreBundle:Default:member }

my_uploads:
    pattern:  /my-uploads
    defaults: { _controller: SOTBCoreBundle:Default:myUploads }



# TRACKER
announce:
    pattern:  /announce
    defaults: { _controller: SOTBCoreBundle:Tracker:announce }

scrape:
    pattern:  /scrape
    defaults: { _controller: SOTBCoreBundle:Tracker:scrape }



# TORRENT
torrent_upload:
    pattern:  /request
    defaults: { _controller: SOTBCoreBundle:Torrent:request }

torrent_vote:
    pattern:  /torrent/{slug}/vote
    defaults: { _controller: SOTBCoreBundle:Torrent:vote }
    requirements:
        _method:  POST

torrent:
    pattern:  /torrent/{slug}
    defaults: { _controller: SOTBCoreBundle:Torrent:show }

torrent_search:
    pattern:  /search
    defaults: { _controller: SOTBCoreBundle:Torrent:search }

torrent_download:
    pattern:  /download/{slug}.torrent
    defaults: { _controller: SOTBCoreBundle:Torrent:download }

torrent_list:
    pattern:  /list
    defaults: { _controller: SOTBCoreBundle:Torrent:list }


# CATEGORIES
category:
    pattern:  /category/{slug}
    defaults: { _controller: SOTBCoreBundle:Torrent:category }

