homepage:
    pattern:  /
    defaults: { _controller: SOTBCoreBundle:Default:index }

members:
    pattern:  /member
    defaults: { _controller: SOTBCoreBundle:Default:member }

announce:
    pattern:  /announce
    defaults: { _controller: SOTBCoreBundle:Default:announce }